
networks:
  traefik:
    name: traefik
    external: true

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt
    restart: always
    networks:
      - traefik
    expose:
      - 1883
      - 9001
    configs:
      - source: mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - source: password_file
        target: /mosquitto/config/password_file
    volumes:
      - mosquitto_data:/mosquitto/data
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.services.mqtt.loadbalancer.server.port=1883"
      - "traefik.tcp.routers.mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mqtt.service=mqtt"

      - "traefik.tcp.services.mqtt_websocket.loadbalancer.server.port=9001"
      - "traefik.tcp.routers.mqtt_websocket.entrypoints=mqtt_websocket"
      - "traefik.tcp.routers.mqtt_websocket.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mqtt_websocket.service=mqtt_websocket"

volumes:
  mosquitto_data: 

configs:
  mosquitto.conf:
    content: |
      listener 1883
      listener 9001
      protocol websockets
      # allow_anonymous true
      password_file /mosquitto/config/password_file
      persistence true
      persistence_location /mosquitto/data/
  password_file:
    # cat password_file | sed -e s/\\$/\\$\\$/g 
    content: |
      wuub:$$7$$101$$MEQ+36fGbliKMiV+$$6PQ+oOTbfO/BnIjECHZ6QE9Q5cJFG1H9E7mmw4NG4SabNmiw08ao7qPkQYLlb26DHvXKTS3jkMZJlLE9dAoT+g==
      wiarus:$$7$$101$$/4IOQtCPatN96sDk$$s/L7c5LGHhNnBPHvAkrhGRbsJO8oTKsjeb9ZSIoR9BjQwKeJwIjbUWPRNcdvQvssoUBQtA+25Q7mFvCOeohAzg==




