networks:
  default:
    name: ldap
  traefik:
    name: traefik
    external: true


volumes:
  lldap_data:
    driver: local

services:
  lldap:
    container_name: ldap
    image: lldap/lldap:stable
    expose:
      - "17170"
    volumes:
      - "lldap_data:/data"
    env_file: "../../secrets/LLDAP_ENV_FILE.plain"
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.tls.certresolver=le-prod"
      - "traefik.http.routers.auth.rule=Host(`ldap.wuub.dev`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
    environment:
      - "LLDAP_LDAP_BASE_DN=dc=wuub,dc=dev"
      - "LLDAP_DATABASE_URL=sqlite:///data/users.db?mode=rwc"

  authelia:
    image: authelia/authelia
    container_name: authelia
