networks:
  default:
    name: ldap

volumes:
  lldap_data:
    driver: local

services:
  lldap:
    container_name: ldap
    image: lldap/lldap:stable
    ports:
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
    env_file: "../../secrets/LLDAP_ENV_FILE.plain"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.tls.certresolver=le-prod"
      - "traefik.http.routers.auth.rule=Host(`auth.wuub.dev`) && PathPrefix(`/ldap`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
    environment:
      - LLDAP_LDAP_BASE_DN=dc=wuub,dc=dev
      - "LLDAP_DATABASE_URL=sqlite:///data/users.db?mode=rwc"
