services:
  maddy:
    image: "foxcpp/maddy:0.7.1"
    container_name: "maddy"
    restart: always
    environment:
      - "MADDY_HOSTNAME=mx.wuub.dev" 
      - "MADDY_DOMAIN=wuub.dev" 
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - "maddy_data:/data"
      - "maddy_state:/var/lib/maddy"
    env_file: "../../secrets/HETZNER_DNS_ACCESS_TOKEN.plain"
    configs:
      - source: maddy.conf
        target: /data/maddy.conf

volumes:
  maddy_data: 
  maddy_state:

configs:
  maddy.conf:
    file: ./maddy.conf

