networks:
  default:
    name: traefik

services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mqtt.address=:1883"
      - "--entrypoints.mqtt_websocket.address=:9001"
      - "--certificatesresolvers.le-staging.acme.tlschallenge=true"
      - "--certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le-staging.acme.email=letsencrypt@wuub.net"
      - "--certificatesresolvers.le-staging.acme.storage=/letsencrypt/acme-staging.json"
      - "--certificatesresolvers.le-prod.acme.tlschallenge=true"
      - "--certificatesresolvers.le-prod.acme.email=letsencrypt@wuub.net"
      - "--certificatesresolvers.le-prod.acme.storage=/letsencrypt/acme-prod.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "9001:9001"
      - "1883:1883"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt_data:/letsencrypt"
    labels:
      # - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.wuub.dev`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.wuub.dev`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le-prod"

volumes:
  letsencrypt_data: 
